version: "3"

## 参考文章1: [docker-compose version3 语法](https://docs.docker.com/compose/compose-file/)
services:
  consul-server1:
    image: consul
    networks:
      consul-net:
        ipv4_address: 172.31.0.2
    ports:
      - 10021:8500
    environment:
      - "CONSUL_LOCAL_CONFIG={\"skip_leave_on_interrupt\": true}"
    command: 
      - agent
      - -server
      - -bootstrap-expect=3
      - -bind=172.31.0.2
      - -node=consul-server1
      - -client=0.0.0.0 ## http接口(8500), 默认为127.0.0.1, 无法发送请求

  consul-server2:
    image: consul
    networks:
      consul-net:
        ipv4_address: 172.31.0.3
    ports:
      - 10031:8500
    environment:
      - "CONSUL_LOCAL_CONFIG={\"skip_leave_on_interrupt\": true}"
    command: 
      - agent
      - -server
      - -bind=172.31.0.3
      - -join=172.31.0.2
      - -node=consul-server2
      - -client=0.0.0.0 ## http接口(8500), 默认为127.0.0.1, 无法发送请求

  consul-server3:
    image: consul
    networks:
      consul-net:
        ipv4_address: 172.31.0.4
    ports:
      - 10041:8500
    environment:
      - "CONSUL_LOCAL_CONFIG={\"skip_leave_on_interrupt\": true}"
    command: 
      - agent
      - -server
      - -bind=172.31.0.4
      - -join=172.31.0.2
      - -node=consul-server3
      - -client=0.0.0.0 ## http接口(8500), 默认为127.0.0.1, 无法发送请求

  consul-client:
    image: consul
    networks:
      consul-net:
        ipv4_address: 172.31.1.2
    ports:
      - 10121:8500
    environment:
      - "CONSUL_LOCAL_CONFIG={\"leave_on_terminate\": true}"
    command: 
      - agent
      - -bind=172.31.1.2
      - -retry-join=172.31.0.2
      - -node=consul-client
      - -client=0.0.0.0 ## http接口(8500), 默认为127.0.0.1, 无法发送请求
      - -ui ## 启用Web UI, 访问路径为`http://localhost:10121/ui`

  ## 用于在compose集群内测试连接(mac下只能连接集群内暴露出的端口, 无法ping通节点)
  test:
    image: generals/centos7
    networks:
      consul-net:
        ipv4_address: 172.31.2.2
    ports:
      - 10221:8500
    command: tail -f /etc/profile

## 创建用于consul集群的网络, 因为consul实例在启动时需要指定IP, 我们需要知道容器启动后的内部IP
networks:
  consul-net:
    driver: bridge
    ipam: 
      driver: default
      config:
        - subnet: 172.31.0.0/16